version: '3.7'

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: espy
    volumes:
      - "~/postgres/data:/var/lib/postgresql/data"